// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDafkCqrbSHZoAnXh7XEkGtBwlK67Z4S6U',
    appId: '1:596553437755:web:7e33bfa32b9cdfe956c21e',
    messagingSenderId: '596553437755',
    projectId: 'coolwallpaper-37',
    authDomain: 'coolwallpaper-37.firebaseapp.com',
    storageBucket: 'coolwallpaper-37.firebasestorage.app',
    measurementId: 'G-LMCGVH7S9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEB3ObavNPrJopg9EWuHN0kHG5kjflXQ8',
    appId: '1:596553437755:android:2abce15ec3ec75c956c21e',
    messagingSenderId: '596553437755',
    projectId: 'coolwallpaper-37',
    storageBucket: 'coolwallpaper-37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtUH_2CQ0l_bSv54lYV4dd8QkGJCVW5lM',
    appId: '1:60749681432:ios:930ac38b3868255db9846d',
    messagingSenderId: '60749681432',
    projectId: 'ppkd-wallpaper',
    storageBucket: 'ppkd-wallpaper.firebasestorage.app',
    iosBundleId: 'com.example.wallpaperApp',
  );

}